//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by beat.rc
//
#define IDS_HIDE                        1
#define IDS_SHOW                        2
#define IDS_DATETIME                    59
#define IDS_LOCAL                       60
#define IDS_TIMEOUT                     61
#define IDS_REGISTER_TITEL              62
#define IDS_REGISTER_TEXT               63
#define IDS_IBEAT                       64
#define IDS_NOTE                        65
#define IDS_FIRST_TITEL                 66
#define IDS_FIRST_TEXT                  67
#define IDS_ALARM                       68
#define IDS_SNTP_OPEN_TITEL             69
#define IDS_SNTP_OPEN_TEXT              70
#define IDS_SNTP_TIMEOUT_TEXT           71
#define IDS_SNTP_TIMEOUT_TITEL          72
#define IDS_LI1_TITEL                   73
#define IDS_LI1_TEXT                    74
#define IDS_LI2_TITEL                   75
#define IDS_LI2_TEXT                    76
#define IDS_DAYS                        77
#define IDS_AUTHOR                      78
#define IDS_INTERNET                    79
#define IDS_BEATS                       80
#define IDS_REGISTER                    81
#define IDS_MOON                        82
#define IDS_AND                         83
#define IDS_2000_TT                     84
#define IDS_BEAT_TT                     85
#define IDS_CBEAT_TT                    86
#define IDS_LOCAL_TT                    87
#define IDS_IDAY_TT                     89
#define IDS_APP_TT                      90
#define IDR_MENU1                       101
#define IDB_BG                          102
#define IDI_SMALL                       103
#define IDW_HEARTBEAT                   105
#define IDW_ALARM                       107
#define IDD_ACTION                      108
#define IDD_SET_ALARM                   109
#define IDC_CURHAND                     109
#define IDD_VIEW_ALARM                  110
#define IDC_HAND_OPEN                   110
#define IDC_HAND_CLOSED                 111
#define IDD_PICK_BUDDY                  112
#define IDD_SET_BUDDY                   113
#define IDD_VIEW_BUDDY                  114
#define IDD_SET_USER                    115
#define IDD_SNTP_SYNC                   116
#define IDD_ABOUT                       118
#define IDD_ABOUT1                      119
#define IDB_HOLGER                      120
#define IDD_T_AUTHOR                    127
#define IDB_MOON                        127
#define IDD_T_INTERNET                  128
#define IDD_T_REGISTER                  129
#define IDD_T_BEATS                     130
#define IDD_T_MOON                      131
#define IDC_CLOSE                       1001
#define IDC_EDIT_TRANSLATE              1002
#define IDC_CLOSE2                      1002
#define IDC_CAMCEL                      1002
#define IDC_EDIT_ALARM                  1003
#define IDC_ALARM                       1004
#define IDC_ALARM_TIME                  1005
#define IDC_TRANSLATE                   1006
#define IDC_DATE                        1007
#define IDC_TRANSLATE2                  1007
#define IDC_TIME                        1008
#define IDC_TRANSLATE3                  1008
#define IDC_REMOVE                      1008
#define IDC_DELETE                      1009
#define IDC_NOW                         1016
#define IDC_LIST1                       1020
#define IDC_EDIT                        1022
#define IDC_EDIT1                       1023
#define IDC_LI                          1023
#define IDC_AGE                         1023
#define IDC_EDIT2                       1024
#define IDC_REFERENCE                   1024
#define IDC_MODE                        1024
#define IDC_FULL                        1024
#define IDC_EDIT3                       1025
#define IDC_STRATUM                     1025
#define IDC_NEW                         1025
#define IDC_EDIT4                       1026
#define IDC_DELAY                       1026
#define IDC_VERSION                     1026
#define IDC_YEAR                        1026
#define IDC_SAVE                        1027
#define IDC_OK                          1028
#define IDC_PASSWORD                    1028
#define IDC_ABORT                       1029
#define IDC_EDIT_REASON                 1030
#define IDC_EDIT_BEATS                  1031
#define IDC_LIST                        1032
#define IDC_MODIFY                      1033
#define IDC_ADD                         1034
#define IDC_EMAIL                       1035
#define IDC_FOOBAR                      1036
#define IDC_LOCATION                    1037
#define IDC_NAME                        1038
#define IDC_CANCEL                      1039
#define IDC_COMBO1                      1046
#define IDC_SYNC                        1052
#define IDC_SET                         1053
#define IDC_SYNC_OFFSET                 1054
#define IDC_AUTO_SYNC                   1055
#define IDC_OFFSET                      1056
#define IDC_SNTP                        1057
#define IDC_STATUS                      1058
#define IDC_READ                        1059
#define IDM_CLOSE                       1060
#define IDM_HOME                        1061
#define IDM_REGISTER                    1062
#define IDC_TIMEOUT                     1063
#define IDC_DELAY2                      1064
#define IDC_TAB1                        1066
#define IDC_TAB                         1066
#define IDC_SDATE                       1067
#define IDC_STIME                       1068
#define IDC_SNOTE                       1069
#define IDC_SREPEAT                     1070
#define IDC_SBEAT                       1071
#define IDC_SINFO_LONG                  1072
#define IDC_SINFO                       1073
#define IDC_SAUTHOR                     1074
#define IDC_SLEGAL                      1075
#define IDC_SLEGAL_LONG                 1076
#define IDC_SCURRENT                    1077
#define IDC_SLEGAL_LONG2                1077
#define IDC_SMANAGE                     1078
#define IDC_SLEGAL_LONG3                1078
#define IDC_SDELAY                      1079
#define IDC_SOFFSET                     1080
#define IDM_MAIL                        1086
#define IDC_MOON                        1087
#define IDC_BUILD                       1101
#define IDM_EXIT                        40001
#define IDM_HIDE                        40002
#define IDM_12H                         40003
#define IDM_24H                         40004
#define IDM_GMT                         40005
#define IDM_NLT                         40006
#define IDM_SHOW                        40007
#define IDM_ABOUT                       40010
#define IDM_NET                         40011
#define IDM_REG                         40012
#define IDM_HEARTBEAT                   40013
#define IDM_ALARM                       40014
#define IDM_COLOR                       40015
#define IDM_FONT                        40017
#define IDM_NORMAL                      40018
#define IDM_SMALL                       40019
#define IDM_ACTION                      40020
#define IDM_TOP                         40021
#define IDM_ALARM_SET                   40023
#define IDM_ALARM_VIEW                  40024
#define IDM_BUDDY_SET                   40025
#define IDM_BUDDY_VIEW                  40026
#define IDM_BUDDY_PICK                  40027
#define ID_MENU_SETTINGS_USERSETUP      40029
#define IDM_USER_SET                    40029
#define IDM_ANLT                        40030
#define IDM_A12H                        40031
#define IDM_A24H                        40032
#define IDM_AGMT                        40033
#define IDM_HELP                        40034
#define IDM_SNTP_SYNC                   40035
#define IDM_SWATCH                      40036
#define IDM_Y2K                         40037
#define IDM_UNIVERSAL                   40037
#define IDM_CENTY                       40038
#define IDM_UDT                         40039

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         40040
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
